#!/bin/sh

start() {
	export DISPLAY=:0
	xclock -geometry 480x480 &
	#twm &
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

