#!/bin/sh 

if grep -qE '\s?splash=false\s?' /proc/cmdline; then
	echo "Boot splashscreen disabled"
	exit 0;
fi

#. /etc/init.d/functions
#. /etc/default/psplash

export TMPDIR=/tmp/.splash
#mount tmpfs -t tmpfs $TMPDIR -o,size=40k

/usr/bin/psplash -n $PARAMS &

# Timetrap against hanging with splash hiding console messages.
(sleep 120; psplash-write "QUIT"; sleep 10; killall -9 psplash) &
