#!/bin/sh
#
# Starts GNSS Power Management
#
# TODO : fix the fact that you can start it twice

NAME=gnsspowerman
FRIENDLYNAME="GNSS Power Manager"
DAEMONDIR=/sbin/sysmgt/
DAEMONEXEC="GNSSPowerManager.sh"
DAEMON=$DAEMONDIR$DAEMONEXEC
PIDFILE=/var/run/$NAME.pid

start() {
	printf "Starting $FRIENDLYNAME: "
	start-stop-daemon --chuid root --start --background --make-pidfile \
		--pidfile "$PIDFILE" \
		-- "$DAEMON"
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	printf "Stopping $FRIENDLYNAME: "
	start-stop-daemon -K -q -p $PIDFILE #&& echo "OK" || echo "Failed"
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	killall -9 $DAEMONEXEC # Tuer tous les process, au cas où
	rm -f $PIDFILE
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

